alertmanager:
  config:
    route:
      group_by: ["alertname", "job"]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      receiver: "gmail-receiver"
      # for alert notification testing
      # routes: []

    receivers:
      - name: "gmail-receiver"
        email_configs:
          - to: "unosega@gmail.com"
            send_resolved: true
