apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: my-custom-rules
  namespace: monitoring
  labels:
    release: prometheus
spec:
  groups:
    - name: kubernetes-alerts
      rules:
        - alert: DeploymentReplicasMismatch
          expr: kube_deployment_spec_replicas != kube_deployment_status_replicas_available
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: "Deployment {{ $labels.deployment }} in namespace {{ $labels.namespace }} does not match its replica."
            description: "Deployment {{ $labels.deployment }} should have {{ $value }} replicas available, but it doesn't."
